#include <iostream>
#include <fstream>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <dirent.h>
#include <fstream>
#include <mutex>
#include <string>
#include <vector>
#include <map>

#include "rpc.h"
#include "mr_protocol.h"

using namespace std;

#define is_valid(c) (c >= 'a' && c <= 'z') || (c >='A' && c <= 'Z')

struct KeyVal {
    string key;
    string val;
};

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
vector<KeyVal> Map(const string &filename, const string &content)
{
	// Copy your code from mr_sequential.cc here.
    // Your code goes here
    // Hints: split contents into an array of words.
    string tmp_str = "";
    vector<KeyVal> ans_vector;
    for (int i = 0; i < content.size(); i++) {
        char current_char = content[i];
        if (is_valid(current_char)) tmp_str += current_char;
        else {
            if (tmp_str != "") {
                KeyVal a;
                a.key = tmp_str;
                a.val = "1";
                ans_vector.push_back(a);
            }
            tmp_str = "";
        }
    }
    return ans_vector;
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
string Reduce(const string &key, const vector < string > &values)
{
    // Copy your code from mr_sequential.cc here.
    int ans = 0;
    for (int i = 0; i < values.size(); i++) ans += atoi(values[i].c_str());
    return to_string(ans);
}


typedef vector<KeyVal> (*MAPF)(const string &key, const string &value);
typedef string (*REDUCEF)(const string &key, const vector<string> &values);

class Worker {
public:
	Worker(const string &dst, const string &dir, MAPF mf, REDUCEF rf);

	void doWork();

private:
	void doMap(int index, const vector<string> &filenames);
	void doReduce(int index);
	void doSubmit(mr_tasktype taskType, int index);

	mutex mtx;
	int id;

	rpcc *cl;
	std::string basedir;
	MAPF mapf;
	REDUCEF reducef;
};


Worker::Worker(const string &dst, const string &dir, MAPF mf, REDUCEF rf)
{
	this->basedir = dir;
	this->mapf = mf;
	this->reducef = rf;

	sockaddr_in dstsock;
	make_sockaddr(dst.c_str(), &dstsock);
	this->cl = new rpcc(dstsock);
	if (this->cl->bind() < 0) {
		printf("mr worker: call bind error\n");
	}
}

void Worker::doMap(int index, const vector<string> &filenames)
{
	// Lab2: Your code goes here.
    vector <KeyVal> ans_kv;
    for (int i = 0; i < filenames.size(); i++) {
        string filename = filenames[i];
        string content;
        getline(ifstream(filename), content, '\0');
        vector<KeyVal> tmp_kv = mapf(filename, content);
        for (int j = 0; j < tmp_kv.size(); j++)ans_kv.push_back(tmp_kv[j]);
    }
    ofstream out_files[REDUCER_COUNT];
    for (int i = 0; i < REDUCER_COUNT; i++) {
        out_files[i].open("mr-" + to_string(index) + "-" + to_string(i) + ".txt");
    }

    for (int i = 0; i < ans_kv.size(); i++) {
        string k = ans_kv[i].key;
        string v = ans_kv[i].val;
        int hash_ans = (k[0] % REDUCER_COUNT);
        out_files[hash_ans] << k << " "<< v << '\n';
    }
    for (int i = 0; i < REDUCER_COUNT; i++) {
        out_files[i].close();
    }
}

void Worker::doReduce(int index) {
	// Lab2: Your code goes here.
    map<string, int> ans_map;
    for (int i = 0; i <= 5; i++) {
        ifstream in;
        string file_path = "mr-" + to_string(i) + '-' + to_string(index) + ".txt";
        in.open(file_path, ios::in);
        string content;
        getline(in, content, '\0');
        if (content == "")  continue;
        stringstream ss(content);
        string str, times;
        while(ss >> str >> times){
            map<string, int>::iterator it = ans_map.find(str);
            if(it != ans_map.end()) ans_map[str]++;
            else ans_map[str] = 1;
        }
    }
    string content;
    for (const pair<string, int> &keyVal: ans_map) {
        content += keyVal.first + ' ' + to_string(keyVal.second) + '\n';
    }
    ofstream out(basedir + "mr-out", ios::out | ios::app);
    out << content << endl;
    out.close();
}

void Worker::doSubmit(mr_tasktype taskType, int index) {
	bool b;
	mr_protocol::status ret = this->cl->call(mr_protocol::submittask, taskType, index, b);
	if (ret != mr_protocol::OK) {
		fprintf(stderr, "submit task failed\n");
		exit(-1);
	}
}

void Worker::doWork()
{
    //
    // Lab2: Your code goes here.
    // Hints: send asktask RPC call to coordinator
    // if mr_tasktype::MAP, then doMap and doSubmit
    // if mr_tasktype::REDUCE, then doReduce and doSubmit
    // if mr_tasktype::NONE, meaning currently no work is needed, then sleep
    //
	for (;;) {
        mr_protocol::AskTaskResponse reply;
        mr_protocol::status  r = cl->call(mr_protocol::asktask, cl->id(), reply);
        mr_tasktype ans = (mr_tasktype)reply.answer;
        if (ans == mr_tasktype::NONE) {
            sleep(0.1);
        }
        else if (ans == mr_tasktype::REDUCE) {
            doReduce(reply.reduceId);
            doSubmit(REDUCE, reply.reduceId);
        }
        else if (ans == mr_tasktype::MAP) {
            vector<string> filenames;
            filenames.push_back(reply.filename);
            doMap(reply.mapId, filenames);
            doSubmit(MAP, reply.mapId);
        }
	}
}

int main(int argc, char **argv)
{
	if (argc != 3) {
		fprintf(stderr, "Usage: %s <coordinator_listen_port> <intermediate_file_dir> \n", argv[0]);
		exit(1);
	}

	MAPF mf = Map;
	REDUCEF rf = Reduce;
	
	Worker w(argv[1], argv[2], mf, rf);
	w.doWork();

	return 0;
}
